language: ruby
sudo: required

rvm:
    - 2.3.0
before_install:
    - "sudo apt-get update -qq"
    - "sudo apt-get install -qq wget curl"
    - "gem install bundler"
    - "wget https://s3.amazonaws.com/aws-cli/awscli-bundle.zip"
    - "unzip awscli-bundle.zip"
    - "sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws"
    - "./awscli-bundle/install -b ~/bin/aws"
    - "./awscli-bundle/install -h"
    - "rm -fr _site/awscli-bundle.zip"
    - "rm -fr _site/awscli-bundle"    
install:
    - "bundle install"
