name: Build and Push to TOR
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        name: Checkout master from this repo
      - name: Checkout submodules associated with this repo
        uses: textbook/git-checkout-submodule-action@1.0.0
      - uses: actions/setup-ruby@v1
        name: Setup Ruby
        with:
          ruby-version: '2.x' # Version range or exact version of a Ruby version to use, using semvers version range syntax.
      - run: rake buildonly
        env:
          GITHUB: true
        name: Run Rakefile from Repository root
      - uses: nolim1t/actions/torscp@0.1.1
        name: Deploy site to hidden service over SCP and TOR
        env:
          SRC: _site
          DEST: ${{ secrets.DEST }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
